from http_client import print_result, request_json, service_url


def main() -> None:
    base_url = service_url("NOTIFICATION_API_URL", "NOTIFICATION_API_PORT", "8103")
    payload = {
        "to": "client@example.local",
        "subject": "Atlas smoke email",
        "body": "Email delivery request generated by the smoke script.",
    }
    status_code, body = request_json("POST", f"{base_url}/messaging/email/messages", payload=payload)
    print_result("notification email", status_code, body)


if __name__ == "__main__":
    main()
