name: rubrica

include:
  - path: ./resources/local.yml
    project_directory: .
  - path: ./services/stripe-cli.yml
    project_directory: .

services:
  postgres:
    extends:
      file: ./services/postgres.yml
      service: local

  redis:
    extends:
      file: ./services/redis.yml
      service: local

  core-api:
    extends:
      file: ./services/core-api.yml
      service: local

  web:
    extends:
      file: ./services/web.yml
      service: local

  auth-api:
    extends:
      file: ./services/auth-api.yml
      service: local

  eventing-api:
    extends:
      file: ./services/eventing-api.yml
      service: local

  notification-api:
    extends:
      file: ./services/notification-api.yml
      service: local

  gateway:
    extends:
      file: ./services/gateway.yml
      service: local

  k6:
    extends:
      file: ./services/k6.yml
      service: local
