name: rubrica-prod

include:
  - path: ./resources/production.yml
    project_directory: .
  - path: ./features/stripe-production-resources.yml
    project_directory: .

services:
  postgres:
    extends:
      file: ./services/postgres.yml
      service: production

  redis:
    extends:
      file: ./services/redis.yml
      service: production

  auth-api:
    extends:
      file: ./services/auth-api.yml
      service: production

  core-api:
    extends:
      file: ./services/core-api.yml
      service: production

  eventing-api:
    extends:
      file: ./services/eventing-api.yml
      service: production

  notification-api:
    extends:
      file: ./services/notification-api.yml
      service: production

  web:
    extends:
      file: ./services/web.yml
      service: production

  gateway:
    extends:
      file: ./services/gateway.yml
      service: production

  cloudflared:
    extends:
      file: ./services/cloudflared.yml
      service: production
