apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api
  namespace: rubrica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      enableServiceLinks: false
      containers:
        - name: core-api
          image: rubrica-core-api:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: rubrica-config
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: core-api
  namespace: rubrica
spec:
  selector:
    app: core-api
  ports:
    - port: 8000
      targetPort: 8000
